In [1]:
import pandas as pd
from pandas import Series
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [2]:
#1.A
#파일읽기
data = pd.read_csv('au4_2500_train.csv')
test = pd.read_csv('au4_2500_test.csv')

#둘 데이터 합치기
total_data = pd.concat([data,test], axis=0)

#결측값 처리해버리기
new_data = total_data.fillna(method ='ffill')
new_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2500 entries, 0 to 499
Columns: 101 entries, V1 to Class
dtypes: float64(55), int64(3), object(43)
memory usage: 1.9+ MB


In [3]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Columns: 101 entries, V1 to Class
dtypes: float64(45), int64(13), object(43)
memory usage: 394.6+ KB


In [4]:
#class를 숫자로 나타내깅
le = LabelEncoder()
new_data.loc[:,'Class'] = le.fit_transform(new_data['Class'])

In [5]:
#일단 숫자들의 coef뽑아버리기
coef = new_data.corr()
display(coef)

V1        V2        V5        V7        V8       V10       V11  \
V1     1.000000 -0.014668 -0.032364 -0.004617  0.028738  0.001164 -0.027987   
V2    -0.014668  1.000000 -0.007895 -0.033043 -0.010324 -0.009479 -0.000507   
V5    -0.032364 -0.007895  1.000000  0.011544 -0.006974 -0.011463  0.010032   
V7    -0.004617 -0.033043  0.011544  1.000000 -0.004035 -0.026820  0.006687   
V8     0.028738 -0.010324 -0.006974 -0.004035  1.000000 -0.024978  0.005713   
V10    0.001164 -0.009479 -0.011463 -0.026820 -0.024978  1.000000  0.022910   
V11   -0.027987 -0.000507  0.010032  0.006687  0.005713  0.022910  1.000000   
V16    0.034403  0.035239 -0.011485 -0.006503  0.031832 -0.012996 -0.044768   
V17    0.002580  0.001859  0.028782  0.014882 -0.004284  0.010422 -0.030751   
V18   -0.023124  0.023582 -0.011008 -0.001438 -0.007392 -0.007340  0.033913   
V20   -0.032091  0.028707  0.015736 -0.011147  0.004444  0.013603  0.031302   
V21    0.001604 -0.012887  0.008510  0.029943 -0.040290 -0.005230  0.027811   
V22    0.016711 -0.009897  0.029888  0.028671 -0.001850 -0.005540  0.004881   
V23    0.020984 -0.036594  0.029468 -0.009334 -0.045093 -0.025940 -0.022156   
V24   -0.037678  0.004931 -0.004913  0.001338 -0.013767  0.018987  0.022128   
V26   -0.010585  0.033316 -0.024775  0.001522 -0.008007 -0.000895  0.010924   
V27   -0.014319  0.004375 -0.042021 -0.003939  0.019867 -0.015829  0.006439   
V28   -0.028970  0.029311  0.013908  0.024707 -0.002635 -0.023603  0.014684   
V29   -0.014301  0.011699  0.014179 -0.008794 -0.038245 -0.002023 -0.004090   
V30    0.005332 -0.004520  0.008746  0.018232  0.001088 -0.013478  0.015388   
V32    0.033771  0.019088 -0.004820 -0.013224  0.011608  0.018090  0.018527   
V33    0.012776 -0.014031  0.014993  0.010217  0.014443 -0.015028 -0.079201   
V35   -0.058581 -0.011602  0.004561  0.026115  0.003798 -0.015328 -0.043494   
V36    0.036969  0.007821  0.020940 -0.037641  0.001368 -0.032325 -0.042136   
V41   -0.018987 -0.006583  0.004718 -0.028454 -0.024990 -0.024319  0.024867   
V42    0.025798 -0.032714 -0.000141 -0.004824  0.023603  0.030698  0.000424   
V43    0.037592  0.023132 -0.015414 -0.002010 -0.028946  0.012423  0.036366   
V45    0.015270 -0.020607 -0.021320  0.021892 -0.038724  0.002645 -0.003850   
V46    0.022208  0.011779  0.031288  0.028375  0.002283  0.006704 -0.006141   
V50    0.021377  0.008822 -0.013310  0.001690 -0.030294 -0.018122  0.000664   
V52   -0.031019 -0.004851 -0.052057 -0.018952  0.032875 -0.016432  0.002712   
V53    0.004651  0.040084  0.014720 -0.015615  0.010090 -0.005653  0.013980   
V54    0.008111  0.018702  0.041636  0.022898  0.025865  0.045478 -0.004058   
V59    0.061285 -0.028282 -0.032898  0.009741  0.002454 -0.001739 -0.031347   
V60    0.021735  0.024945 -0.015835  0.017120 -0.002390 -0.013963  0.015749   
V61    0.007912 -0.074774  0.005574  0.014676 -0.014835 -0.040117  0.007163   
V62   -0.001287  0.010228  0.001905  0.044589 -0.020794  0.004600  0.010434   
V63   -0.019915  0.009530  0.028743 -0.026972  0.023595  0.009790 -0.021424   
V65   -0.006225 -0.014403 -0.009796 -0.003893  0.003077 -0.001028  0.034181   
V67    0.004108 -0.020534 -0.025834 -0.051242  0.000880 -0.044175  0.007040   
V70   -0.017883  0.003615 -0.048628  0.010347 -0.023101  0.016907 -0.016308   
V71    0.041187  0.050823 -0.024103 -0.013891 -0.004259 -0.019901 -0.001088   
V72   -0.000704  0.017887  0.002455 -0.041034 -0.011365  0.015751  0.038043   
V73    0.011429  0.011758 -0.042330 -0.031588 -0.003843 -0.022080 -0.014268   
V74   -0.016757 -0.051951  0.003174 -0.017908  0.003958 -0.008576  0.005426   
V75   -0.003184 -0.014352 -0.016785  0.013101 -0.027319  0.008712  0.017509   
V76   -0.046519 -0.019447 -0.006938  0.049241  0.004538 -0.034648  0.010556   
V77    0.030660 -0.009956  0.033930 -0.018754  0.026276  0.013409 -0.004454   
V78   -0.007813 -0.019343 -0.003395 -0.009949 -0.010014 -0.016197 -0.003048   
V80    0.015296  0.000937  0.026528 -0.024427 -0.012919  0.0207

In [6]:
#가장관련된 coef뽑기위해 sorting
unsortcoef = pd.DataFrame(coef['Class'])
unsortcoef

Class
V1     0.001390
V2    -0.024309
V5    -0.021938
V7    -0.013870
V8     0.125332
V10    0.019240
V11   -0.018615
V16    0.053247
V17   -0.040637
V18    0.004507
V20    0.010613
V21    0.001395
V22   -0.013361
V23   -0.012913
V24   -0.014324
V26    0.010720
V27    0.039700
V28   -0.017549
V29   -0.000195
V30    0.019348
V32   -0.012494
V33    0.022759
V35    0.015746
V36    0.017807
V41    0.017375
V42    0.002165
V43   -0.014833
V45   -0.015635
V46    0.000883
V50   -0.038352
V52   -0.004576
V53   -0.016123
V54   -0.018669
V59   -0.012957
V60    0.012415
V61    0.015006
V62   -0.030538
V63    0.020023
V65    0.020915
V67    0.005636
V70   -0.000085
V71   -0.001371
V72   -0.016645
V73    0.022987
V74    0.027743
V75   -0.030027
V76    0.001630
V77   -0.002471
V78   -0.027397
V80    0.021319
V82   -0.004212
V85    0.056980
V86   -0.011909
V87   -0.013794
V88    0.030425
V91    0.040951
V94    0.000862
V95   -0.003025
Class  1.000000

In [7]:
sortcoef = unsortcoef.sort_values(by=['Class'])
sortcoef

Class
V17   -0.040637
V50   -0.038352
V62   -0.030538
V75   -0.030027
V78   -0.027397
V2    -0.024309
V5    -0.021938
V54   -0.018669
V11   -0.018615
V28   -0.017549
V72   -0.016645
V53   -0.016123
V45   -0.015635
V43   -0.014833
V24   -0.014324
V7    -0.013870
V87   -0.013794
V22   -0.013361
V59   -0.012957
V23   -0.012913
V32   -0.012494
V86   -0.011909
V52   -0.004576
V82   -0.004212
V95   -0.003025
V77   -0.002471
V71   -0.001371
V29   -0.000195
V70   -0.000085
V94    0.000862
V46    0.000883
V1     0.001390
V21    0.001395
V76    0.001630
V42    0.002165
V18    0.004507
V67    0.005636
V20    0.010613
V26    0.010720
V60    0.012415
V61    0.015006
V35    0.015746
V41    0.017375
V36    0.017807
V10    0.019240
V30    0.019348
V63    0.020023
V65    0.020915
V80    0.021319
V33    0.022759
V73    0.022987
V74    0.027743
V88    0.030425
V27    0.039700
V91    0.040951
V16    0.053247
V85    0.056980
V8     0.125332
Class  1.000000

In [8]:
#V91	0.040951
#V16	0.051956
#V85	0.058001
#V8	0.123853
pick_feature = ['V91','V16','V85','V8']
norm_X_train = new_data[pick_feature]
norm_X_train.info()
#norm_Y_train = data['Class']
#norm_Y_train

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2500 entries, 0 to 499
Data columns (total 4 columns):
V91    2500 non-null int64
V16    2500 non-null float64
V85    2500 non-null float64
V8     2500 non-null float64
dtypes: float64(3), int64(1)
memory usage: 97.7 KB


In [9]:
from sklearn.preprocessing import MinMaxScaler
#정규화하기
scaler = MinMaxScaler()
scaler.fit(norm_X_train)
np_norm_total_data = scaler.transform(norm_X_train)
norm_total_data = pd.DataFrame(np_norm_total_data)
norm_total_data.describe()

0            1            2            3
count  2500.000000  2500.000000  2500.000000  2500.000000
mean      0.525800     0.503550     0.260787     0.508133
std       0.400373     0.284740     0.272667     0.330689
min       0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.291667     0.071770     0.333333
50%       0.500000     0.458333     0.148325     0.666667
75%       1.000000     0.750000     0.388756     0.666667
max       1.000000     1.000000     1.000000     1.000000

In [10]:
#다시 테스트와 트레인데이터로 나누기 
#원래대로 train과 test데이터로 나누기 
norm_train = norm_total_data.loc[:1999,:]
norm_test = norm_total_data.loc[2000:,:]
norm_train.info()
norm_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
0    2000 non-null float64
1    2000 non-null float64
2    2000 non-null float64
3    2000 non-null float64
dtypes: float64(4)
memory usage: 62.6 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 2000 to 2499
Data columns (total 4 columns):
0    500 non-null float64
1    500 non-null float64
2    500 non-null float64
3    500 non-null float64
dtypes: float64(4)
memory usage: 15.7 KB


In [11]:
Y_train = data['Class']
Y_train
#Y_test = test['Class']

0       class2
1       class2
2       class1
3       class3
4       class2
5       class2
6       class1
7       class2
8       class1
9       class2
10      class2
11      class2
12      class1
13      class2
14      class3
15      class2
16      class1
17      class1
18      class1
19      class1
20      class1
21      class3
22      class2
23      class1
24      class1
25      class1
26      class1
27      class1
28      class2
29      class2
         ...  
1970    class1
1971    class1
1972    class1
1973    class1
1974    class2
1975    class2
1976    class2
1977    class2
1978    class1
1979    class1
1980    class1
1981    class1
1982    class1
1983    class1
1984    class2
1985    class2
1986    class2
1987    class2
1988    class1
1989    class1
1990    class1
1991    class1
1992    class2
1993    class2
1994    class2
1995    class1
1996    class2
1997    class1
1998    class2
1999    class1
Name: Class, Length: 2000, dtype: object

In [12]:
#1.B 5-NN분류기 사용
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(norm_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [13]:
#Y= knn.predict(norm_test)
test = knn.score(norm_test,Y_test)##test accuracy
train = knn.score(norm_train, Y_train)#training accuracy
display(test)
display(train)

NameError: name 'Y_test' is not defined

In [14]:
#dummy해보기
new_data.loc[:,'Class'] = le.fit_transform(new_data['Class'])
classdata = new_data['Class']

data_dummies = pd.get_dummies(new_data) ## get_dummies onhot인코딩 해주는거 
data_dummies.head()

V1   V2    V5   V7   V8  V10      V11   V16    V17   V18   ...     V98_v4  \
0   1  3.0  0.22  0.0  1.0  2.0  34231.0  0.51  788.0  31.1   ...          0   
1   0  0.0  0.41  0.0  2.0  0.0  71919.0  0.28  341.0  33.7   ...          0   
2   0  2.0  0.06  0.0  2.0  0.0  72055.0  0.30  792.0  35.4   ...          0   
3   0  3.0  0.49  1.0  3.0  3.0  71946.0  0.31  738.0  32.9   ...          0   
4   1  0.0  0.04  0.0  2.0  0.0  39969.0  0.10  843.0  35.1   ...          0   

   V98_v5  V98_v6  V99_v1  V99_v2  V100_v1  V100_v2  V100_v3  V100_v4  V100_v5  
0       0       1       0       1        0        1        0        0        0  
1       0       0       1       0        0        0        0        1        0  
2       0       0       0       1        0        0        0        1        0  
3       1       0       1       0        1        0        0        0        0  
4       0       0       1       0        0        0        0        0        1  

[5 rows x 228 columns]

In [15]:
data_dummies['Class'] = classdata

In [16]:
data_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2500 entries, 0 to 499
Columns: 228 entries, V1 to V100_v5
dtypes: float64(55), int64(4), uint8(169)
memory usage: 1.5 MB


In [17]:
coef = data_dummies.corr()
display(coef)

V1        V2        V5        V7        V8       V10       V11  \
V1       1.000000 -0.014668 -0.032364 -0.004617  0.028738  0.001164 -0.027987   
V2      -0.014668  1.000000 -0.007895 -0.033043 -0.010324 -0.009479 -0.000507   
V5      -0.032364 -0.007895  1.000000  0.011544 -0.006974 -0.011463  0.010032   
V7      -0.004617 -0.033043  0.011544  1.000000 -0.004035 -0.026820  0.006687   
V8       0.028738 -0.010324 -0.006974 -0.004035  1.000000 -0.024978  0.005713   
V10      0.001164 -0.009479 -0.011463 -0.026820 -0.024978  1.000000  0.022910   
V11     -0.027987 -0.000507  0.010032  0.006687  0.005713  0.022910  1.000000   
V16      0.034403  0.035239 -0.011485 -0.006503  0.031832 -0.012996 -0.044768   
V17      0.002580  0.001859  0.028782  0.014882 -0.004284  0.010422 -0.030751   
V18     -0.023124  0.023582 -0.011008 -0.001438 -0.007392 -0.007340  0.033913   
V20     -0.032091  0.028707  0.015736 -0.011147  0.004444  0.013603  0.031302   
V21      0.001604 -0.012887  0.008510  0.029943 -0.040290 -0.005230  0.027811   
V22      0.016711 -0.009897  0.029888  0.028671 -0.001850 -0.005540  0.004881   
V23      0.020984 -0.036594  0.029468 -0.009334 -0.045093 -0.025940 -0.022156   
V24     -0.037678  0.004931 -0.004913  0.001338 -0.013767  0.018987  0.022128   
V26     -0.010585  0.033316 -0.024775  0.001522 -0.008007 -0.000895  0.010924   
V27     -0.014319  0.004375 -0.042021 -0.003939  0.019867 -0.015829  0.006439   
V28     -0.028970  0.029311  0.013908  0.024707 -0.002635 -0.023603  0.014684   
V29     -0.014301  0.011699  0.014179 -0.008794 -0.038245 -0.002023 -0.004090   
V30      0.005332 -0.004520  0.008746  0.018232  0.001088 -0.013478  0.015388   
V32      0.033771  0.019088 -0.004820 -0.013224  0.011608  0.018090  0.018527   
V33      0.012776 -0.014031  0.014993  0.010217  0.014443 -0.015028 -0.079201   
V35     -0.058581 -0.011602  0.004561  0.026115  0.003798 -0.015328 -0.043494   
V36      0.036969  0.007821  0.020940 -0.037641  0.001368 -0.032325 -0.042136   
V41     -0.018987 -0.006583  0.004718 -0.028454 -0.024990 -0.024319  0.024867   
V42      0.025798 -0.032714 -0.000141 -0.004824  0.023603  0.030698  0.000424   
V43      0.037592  0.023132 -0.015414 -0.002010 -0.028946  0.012423  0.036366   
V45      0.015270 -0.020607 -0.021320  0.021892 -0.038724  0.002645 -0.003850   
V46      0.022208  0.011779  0.031288  0.028375  0.002283  0.006704 -0.006141   
V50      0.021377  0.008822 -0.013310  0.001690 -0.030294 -0.018122  0.000664   
...           ...       ...       ...       ...       ...       ...       ...   
V89_v5   0.004716 -0.005523 -0.012053  0.001457  0.017336  0.003673  0.016553   
V89_v6   0.013052 -0.002513  0.038982 -0.045637 -0.012401  0.007196 -0.019124   
V90_v1  -0.012414 -0.038845  0.019449  0.024753 -0.022585 -0.001436 -0.022026   
V90_v2   0.025048  0.039798 -0.026174 -0.008643 -0.011710  0.027035  0.009980   
V90_v3  -0.013138 -0.001076  0.007021 -0.016663  0.035538 -0.026567  0.012451   
V92_v1   0.019131 -0.018351 -0.020280 -0.030866  0.018887  0.000027 -0.022044   
V92_v2  -0.019131  0.018351  0.020280  0.030866 -0.018887 -0.000027  0.022044   
V93_v1   0.028231 -0.007423 -0.016530  0.029683 -0.020396 -0.002722 -0.003834   
V93_v2  -0.028231  0.007423  0.016530 -0.029683  0.020396  0.002722  0.003834   
V96_v1   0.010354 -0.002758  0.000009 -0.036890 -0.021137  0.015766  0.008996   
V96_v2  -0.008845 -0.025251 -0.042419 -0.005320 -0.008411  0.015220  0.011885   
V96_v3  -0.009766 -0.002617  0.024528 -0.024541  0.035001 -0.035617 -0.005537   
V96_v4  -0.008530  0.002115  0.012862  0.060538 -0.008559 -0.002375 -0.002760   
V96_v5   0.015914  0.028806  0.007029  0.009992  0.003707  0.005571 -0.013085   
V97_v1  -0.016932 -0.006774 -0.002396 -0.003138 -0.006816 -0.013737 -0.015716   
V97_v2   0.043800  0.012240 -0.012907  0.002244  0.034063  0.004078 -0.018979   
V97_v3  -0.027183 -0.005512  0.015548  0.000925 -0.027623  0.009881  0.035306   
V98_v1  -0.030345 -0.010108  0.002339 -0.02715

In [18]:
unsortcoef = pd.DataFrame(coef['Class'])

In [19]:
sortcoef = unsortcoef.sort_values(by=['Class'])
# correlation coefficient가 높은 5개의 feature 뽑기위해 소팅하기 

In [20]:
sortcoef

Class
V51_v4  -0.215025
V3_v4   -0.076181
V55_v3  -0.063638
V3_v2   -0.053870
V69_v2  -0.051877
V98_v5  -0.046782
V31_v1  -0.046044
V81_v2  -0.044343
V17     -0.040637
V50     -0.038352
V64_v3  -0.037963
V3_v3   -0.036655
V69_v3  -0.036218
V15_v1  -0.034912
V56_v4  -0.034759
V40_v2  -0.033722
V90_v3  -0.032720
V62     -0.030538
V38_v1  -0.030466
V14_v2  -0.030064
V75     -0.030027
V96_v1  -0.030001
V19_v2  -0.029268
V25_v4  -0.028552
V12_v3  -0.027882
V78     -0.027397
V51_v5  -0.027084
V79_v2  -0.026363
V48_v2  -0.025706
V58_v3  -0.025656
...           ...
V90_v1   0.027230
V74      0.027743
V47_v6   0.027976
V96_v3   0.028003
V19_v1   0.029268
V55_v2   0.029369
V44_v1   0.029389
V3_v6    0.030288
V88      0.030425
V15_v6   0.031191
V25_v3   0.031800
V12_v2   0.031866
V64_v2   0.032852
V40_v1   0.033722
V100_v1  0.034609
V27      0.039700
V3_v1    0.040128
V91      0.040951
V81_v1   0.042675
V55_v4   0.045487
V31_v2   0.046044
V38_v4   0.051628
V16      0.053247
V85      0.056980
V69_v1   0.072670
V51_v2   0.092264
V3_v5    0.094928
V8       0.125332
V51_v3   0.135626
Class    1.000000

[228 rows x 1 columns]

In [21]:
pick_feature_from_dummy = ['V51','V8','V3','V69']

In [22]:
#1.B 5-NN분류기 사용
from sklearn.neighbors import KNeighborsClassifier
#결측값처리
datadata = data.fillna(method ='ffill')
knn = KNeighborsClassifier(n_neighbors=5)
X_train = datadata[pick_feature_from_dummy]
Y_train = data['Class']

In [23]:
X_train.info()
#object를 숫자로 바꾸깅

X_train.loc[:,'V3'] = le.fit_transform(X_train['V3'])
X_train.loc[:,'V51'] = le.fit_transform(X_train['V51'])
X_train.loc[:,'V69'] = le.fit_transform(X_train['V69'])


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
V51    2000 non-null object
V8     2000 non-null float64
V3     2000 non-null object
V69    2000 non-null object
dtypes: float64(1), object(3)
memory usage: 62.6+ KB


C:\Users\carpe\Anaconda3\lib\site-packages\pandas\core\indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [24]:
#정규화하기
X_test_normalized = (X_test - X_test.mean()) / X_test.std()

NameError: name 'X_test' is not defined

In [25]:
knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [26]:
#테스트데이터넣어서 확인해보기 
test22 = pd.read_csv('au4_2500_test.csv')
test_data = test22.fillna(method ='ffill')

X_test = test_data[pick_feature_from_dummy]
X_test.info()
#object값 변경
X_test.loc[:,'V3'] = le.fit_transform(X_test['V3'])
X_test.loc[:,'V51'] = le.fit_transform(X_test['V51'])
X_test.loc[:,'V69'] = le.fit_transform(X_test['V69'])
#정규화하기
X_test_normalized = (X_test - X_test.mean()) / X_test.std()


Y_test = test_data['Class']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
V51    500 non-null object
V8     500 non-null int64
V3     500 non-null object
V69    500 non-null object
dtypes: int64(1), object(3)
memory usage: 15.7+ KB


C:\Users\carpe\Anaconda3\lib\site-packages\pandas\core\indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [27]:
Y= knn.predict(X_test)
test = knn.score(X_test,Y_test)##test accuracy
train = knn.score(X_train, Y_train)#training accuracy
display(test)
display(train)

0.608

0.724

In [28]:
## 선택된 featrue 섞어보기 
final_pick = ['V51','V8','V3']
final_data_X_train = data[final_pick]

In [29]:
##knn사용
final_data_X_train = final_data_X_train.fillna(method ='ffill')
final_data_X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
V51    2000 non-null object
V8     2000 non-null float64
V3     2000 non-null object
dtypes: float64(1), object(2)
memory usage: 47.0+ KB


In [30]:
final_data_X_train.loc[:,'V3'] = le.fit_transform(final_data_X_train['V3'])
final_data_X_train.loc[:,'V51'] = le.fit_transform(final_data_X_train['V51'])
#final_data_X_train.loc[:,'V100'] = le.fit_transform(final_data_X_train['V100'])


In [31]:
final_X_train_normalized = (final_data_X_train - final_data_X_train.mean()) / final_data_X_train.std()
final_Y_train = data['Class']

In [32]:
knn.fit(final_X_train_normalized, final_Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [33]:
#테스트데이터넣어서 확인해보기 
final_test = pd.read_csv('au4_2500_test.csv')
final_test = final_test.fillna(method ='ffill')

final_X_test = final_test[final_pick]
final_X_test.info()
#object값 변경
final_X_test.loc[:,'V3'] = le.fit_transform(final_X_test['V3'])
final_X_test.loc[:,'V51'] = le.fit_transform(final_X_test['V51'])
#final_X_test.loc[:,'V100'] = le.fit_transform(final_X_test['V100'])
#정규화하기
final_X_test_normalized = (final_X_test - final_X_test.mean()) / final_X_test.std()


final_Y_test = test_data['Class']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
V51    500 non-null object
V8     500 non-null int64
V3     500 non-null object
dtypes: int64(1), object(2)
memory usage: 11.8+ KB


C:\Users\carpe\Anaconda3\lib\site-packages\pandas\core\indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [34]:
final_test = knn.score(final_X_test_normalized,final_Y_test)##test accuracy
final_train = knn.score(final_X_train_normalized, final_Y_train)#training accuracy
display(final_test)
display(final_train)

0.648

0.648

In [35]:
# Decision tree 분류기
from sklearn.tree import DecisionTreeClassifier
tree_model = DecisionTreeClassifier()
tree_model.fit(final_X_train_normalized, final_Y_train)
test = tree_model.score(final_X_test_normalized,final_Y_test)
train = tree_model.score(final_X_train_normalized, final_Y_train)
print(test)
print(train)

0.658
0.6685


In [36]:
#SVM 
from sklearn.svm import SVC
svm_model = SVC()
svm_model.fit(final_X_train_normalized, final_Y_train)
test = svm_model.score(final_X_test_normalized,final_Y_test)
train = svm_model.score(final_X_train_normalized, final_Y_train)
print(test)
print(train)

0.628
0.6255


In [37]:
#데이터분석2
#최적의 k값 찾기
from sklearn.model_selection import cross_val_score
k_list = list(range(1,30))
k_list = list(filter(lambda x: x%2 == 1, k_list))
knn_error = []

knn_score = []

In [38]:
k_list

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [39]:
from sklearn.model_selection import train_test_split
for k in k_list:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(final_X_train_normalized, final_Y_train)
    aaaa = knn.score(final_X_test_normalized,final_Y_test)
    knn_score.append(aaaa)
    print(aaaa + k)
max(knn_score)
#k가 9일때 최대가된다 

1.584
3.63
5.648
7.636
9.662
11.66
13.656
15.656
17.654
19.658
21.656
23.656
25.648
27.648
29.638


0.662

In [40]:
#k가 9일때 0.662 으로 최대값이다 .
knn3 = KNeighborsClassifier(n_neighbors=9)
knn3.fit(final_X_train_normalized, final_Y_train)

final_test = knn3.score(final_X_test_normalized,final_Y_test)##test accuracy
final_train = knn3.score(final_X_train_normalized, final_Y_train)#training accuracy
display(final_test)
display(final_train)

0.662

0.6495

In [41]:
#svm 최적화 
from sklearn import svm
import numpy as np
#C가 크면 허용범위가 작아짐 즉 엄격해짐 
#gamma 바꿔보기
for i in range(1,5):
    clf = svm.SVC(gamma=i, C=1)
    clf.fit(final_X_train_normalized, final_Y_train)
    clf.predict(final_X_test_normalized)
    a = clf.score(final_X_test_normalized,final_Y_test)
    print( clf.score(final_X_test_normalized,final_Y_test))
    #gamma가 2일때 최대값을 가짐 

0.65
0.656
0.654
0.66


In [42]:
#c 최적값을 위해 test
c_list = list(range(1,30))
c_list = list(filter(lambda x: x%2 == 1, c_list))

svm_error = []
svm_score = []
c_list

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [43]:
for c in c_list:
    svm_cv2 = svm.SVC(gamma=2, C=c)
    svm_cv2.fit(final_X_train_normalized, final_Y_train)
    svm_score = svm_cv2.score(final_X_test_normalized,final_Y_test)
    print(svm_score)
# c가 3이상이면 0.66으로 나온다 

0.656
0.66
0.66
0.66
0.66
0.66
0.66
0.66
0.66
0.66
0.66
0.66
0.66
0.66
0.66


In [44]:
#confusion matrix
#9knn일때 매트릭스 
from sklearn.metrics import confusion_matrix, classification_report
Y_pred = knn3.predict(final_X_test_normalized)
confusion = confusion_matrix(final_Y_test, Y_pred)
print(confusion)
print(classification_report(final_Y_test, Y_pred))

[[181  58   0]
 [ 70 150   0]
 [ 16  25   0]]
             precision    recall  f1-score   support

     class1       0.68      0.76      0.72       239
     class2       0.64      0.68      0.66       220
     class3       0.00      0.00      0.00        41

avg / total       0.61      0.66      0.63       500



C:\Users\carpe\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [45]:
#confusion matrix
#gamma가 2 c가 3이상의 svm의 매트릭스 
svm_cv3 = svm.SVC(gamma=2, C=3)
svm_cv3.fit(final_X_train_normalized, final_Y_train)
Y_pred2 = svm_cv3.predict(final_X_test_normalized)
confusion2 = confusion_matrix(final_Y_test, Y_pred2)
print(confusion2)
print(classification_report(final_Y_test, Y_pred2))

[[178  61   0]
 [ 68 152   0]
 [ 15  26   0]]
             precision    recall  f1-score   support

     class1       0.68      0.74      0.71       239
     class2       0.64      0.69      0.66       220
     class3       0.00      0.00      0.00        41

avg / total       0.61      0.66      0.63       500



C:\Users\carpe\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [46]:
#randomforest 모델 사용
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [47]:
# 생성된 모델을 train 데이터를 사용하여 학습시킵니다.
rf.fit(final_X_train_normalized, final_Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [48]:
rf.predict(final_X_test_normalized)

array(['class1', 'class1', 'class1', 'class1', 'class1', 'class1',
       'class1', 'class2', 'class1', 'class1', 'class1', 'class2',
       'class1', 'class1', 'class2', 'class2', 'class1', 'class1',
       'class2', 'class1', 'class1', 'class2', 'class1', 'class2',
       'class2', 'class1', 'class1', 'class1', 'class1', 'class1',
       'class2', 'class2', 'class2', 'class1', 'class2', 'class1',
       'class2', 'class1', 'class2', 'class2', 'class2', 'class2',
       'class2', 'class2', 'class1', 'class1', 'class1', 'class2',
       'class1', 'class1', 'class2', 'class2', 'class1', 'class1',
       'class2', 'class2', 'class2', 'class1', 'class2', 'class2',
       'class2', 'class1', 'class2', 'class1', 'class1', 'class1',
       'class1', 'class1', 'class1', 'class2', 'class2', 'class1',
       'class1', 'class2', 'class2', 'class1', 'class2', 'class1',
       'class2', 'class2', 'class2', 'class2', 'class2', 'class1',
       'class2', 'class2', 'class1', 'class2', 'class1', 'clas

In [49]:
# 각각의 test데이터의 3가지 class에 대한 확률을 나타냅니다.
rf.predict_proba(final_X_test_normalized)

array([[0.92259143, 0.07740857, 0.        ],
       [0.56497263, 0.35836747, 0.07665989],
       [0.54796667, 0.45203333, 0.        ],
       ...,
       [0.51722602, 0.44719858, 0.0355754 ],
       [0.46575923, 0.31691565, 0.21732512],
       [0.40485481, 0.52817657, 0.06696862]])

In [50]:
rf.score(final_X_test_normalized,final_Y_test)

0.65

In [51]:
## Cunfusion matrix 생성하기
cross = pd.crosstab(final_Y_test, rf.predict(final_X_test_normalized), rownames=['Actual class'], colnames=['Predicted class'])
cross

Predicted class  class1  class2
Actual class                   
class1              174      65
class2               69     151
class3               11      30

In [52]:
cccc = []
svm_cv2 = svm.SVC(gamma=2, C=5)
svm_cv2.fit(final_X_train_normalized, final_Y_train)
cccc.append(svm_cv2.predict(final_X_test_normalized))

In [57]:
final3 = pd.DataFrame(svm_cv2.predict(final_X_test_normalized))
final3



0
0    class1
1    class1
2    class1
3    class1
4    class1
5    class1
6    class1
7    class2
8    class1
9    class1
10   class1
11   class2
12   class1
13   class2
14   class2
15   class2
16   class1
17   class1
18   class2
19   class1
20   class1
21   class1
22   class1
23   class2
24   class2
25   class2
26   class1
27   class1
28   class1
29   class1
..      ...
470  class1
471  class1
472  class1
473  class1
474  class1
475  class1
476  class1
477  class2
478  class2
479  class2
480  class1
481  class2
482  class2
483  class1
484  class2
485  class1
486  class2
487  class2
488  class1
489  class1
490  class2
491  class2
492  class2
493  class1
494  class2
495  class2
496  class1
497  class1
498  class1
499  class2

[500 rows x 1 columns]

In [59]:
len(final3)

500

In [64]:
final3[0][0]

'class1'

In [65]:
with open(" homework2_result_opt.csv.", "w") as f:
    for i in range(len(final3)):
        f.write((str)(final3[0][i])+'\n')